### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adelevie**
See https://github.com/sinatra/rack-protection/issues/101

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
i very much support this change. great call!

**Comment by TrevorBramble** [comment]
:+1: :+1:

**Comment by ngauthier** [comment]
this is still in the project description here:

https://github.com/sinatra/rack-protection

(needs to be edited via github ui)

**Comment by adelevie** [comment]
:thumbsup: !!!

**Pull request merged**
