### PR TITLE
Upgrade to RSpec 3 and major specs refactoring

### PR DESCRIPTION
**Pull request by mdesantis**
Hello,

I'm planning to work a bit on rack-protection performance, so I cloned the project and I found the specs a bit cluttered; so I upgraded to RSpec 3 and did a cleanup.

These are my edits:

* 022f994: Convert RSpec syntax from RSpec 2 to RSpec 3 using the wonderful tool [Transpec](http://yujinakayama.me/transpec/)
* 2674740: Upgrade development dependency from RSpec 2 to RSpec 3
* de797ce: Move spec files from a flat spec/*_spec.rb pattern to the conventional pattern lib/folder/file.rb -> spec/lib/folder/file_spec.rb
* 01902df: Remove some define_methods on Struct.new classes in favour of `Struct.new do; def ... ; end` syntax
* 941fee8: Remove execution permissions to some spec files
* ed57eb2: Fix Ruby warnings visible using `rspec --warning`
* ecae614: Fix a test which implementation was previously broken (more on this later)
* 8196555: Remove unnedeed `require 'stringio'` line
* c5020a2:  Reorganize spec directives which previously were collected in spec_helper.rb into relative spec/support/*.rb files
* a00a021: Generate rspec init default files with `rspec --init` and merge the previous ones into them
* 513abea: Remove `require 'spec_helper'` not needed anymore (because `.rspec` now includes `--require spec_helper` option)

The only change which involves a change to a test is ecae614: I replaced the previous incorrect use of `should` inside a define_method with a mock, and then realized that the test was broken, because the `changer` middleware was called *after* the `detector`; so I switched them and fixed the test.

I hope my changes to be appreciated :)

### CODE REVIEW

**Comment by mdesantis** [comment]
News about this pull request? It seems to be abandoned... @rkh can I please ask your attention?

**Comment by kytrinyx** [comment]
@mdesantis I'm going to spend some time looking at rack-protection this weekend, and will figure out if there's something that needs to be done to get this merged.

There are 26 failing tests against jruby-head, with `undefined method 'call' for #<#<Class:0x7752d052>:0x3468e86e>`, but jruby-stable is passing. We'll need to figure out if it's a regression in jruby and report it there, or if there's some odd edge case that we are running into here.

**Comment by mdesantis** [comment]
Just curious... why do you test against heads? Are they supposed to be stable?

**Comment by kytrinyx** [comment]
They're not supposed to be stable, but it's a good way of catching new issues early (and help catch regressions in the language implementations)

**Comment by kytrinyx** [comment]
I got food poisoning, which screwed up my weekend plans pretty significantly. I haven't been able to get to any of what I had planned, unfortunately, but this is still at the top of my list.

Sorry about that.

**Comment by mdesantis** [comment]
I got food poisoning on last Friday too :-S no problem, thank you for the
update

--

Maurizio De Santis

2015-03-30 4:55 GMT+02:00 Katrina Owen <notifications@github.com>:

**Comment by kytrinyx** [comment]
I reran this against jruby-head, and it passed just fine. Not sure what happened back in the day. Thank you so much, @mdesantis, for taking the time to upgrade the specs, and I apologize for the delay in getting this merged.

**Pull request merged**
